# Generated by Django 4.2 on 2025-03-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_pic',
        ),
        migrations.AddField(
            model_name='post',
            name='selected_picture',
            field=models.ImageField(blank=True, null=True, upload_to='selected_pics/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='album',
            field=models.ImageField(blank=True, null=True, upload_to='albums/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='classification',
            field=models.CharField(blank=True, choices=[('professional', 'Professional Weblog'), ('social', 'Social Weblog'), ('portfolio', 'Portfolio'), ('personal', 'Personal Weblog'), ('coaching', 'Coaching Page')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='passage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
