# Generated by Django 4.2 on 2025-03-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0002_remove_post_post_pic_post_selected_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='privacy',
            field=models.CharField(blank=True, choices=[('public', 'Public'), ('private', 'Private')], max_length=10, null=True),
        ),
    ]
